services:
  neo4j:
    image: neo4j:5.15-community
    container_name: pfi-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/pfi_graph_test
    volumes:
      - ./neo4j_data:/data
